apiVersion: v1
kind: List
items:
#  - apiVersion: v1
#    kind: Service
#    metadata:
#      name: customer-service
#    spec:
#      ports:
#        - port: 8080
#          targetPort: 8080
#      selector:
#        deploymentconfig: customer-service
#  - apiVersion: v1
#    kind: DeploymentConfig
#    metadata:
#      name: customer-service
#    spec:
#      replicas: 2
#      selector:
#        deploymentconfig: customer-service
#      strategy:
#        # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
#        type: Recreate
#      template:
#        metadata:
#          labels:
#            deploymentconfig: customer-service
#        spec:
#          containers:
#            - image: debangsud/customer-service
#              name: customer-service
#              ports:
#                - containerPort: 8080
#                  protocol: TCP
#      triggers:
#        - type: ConfigChange
#        - imageChangeParams:
#            automatic: true
#            containerNames:
#              - customer-service
#            from:
#              kind: ImageStreamTag
#              name: debangshud/customer-service:latest
#          type: ImageChange
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: customer-service
      namespace: doodle
    spec:
      tags:
        from:
          kind: DockerImage
          name: debangshud/customer-service
        name: latest
#  - apiVersion: v1
#    kind: Route
#    metadata:
#      name: customer-service
#    spec:
#      to:
#        kind: Service
#        name: customer-service